[package]
name = "tsan-analyzer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["native-tsduck"]
native-tsduck = ["dep:tsan-tsduck-sys", "tsan-tsduck-sys/native"]

[dependencies]
tsan-core = { path = "../tsan-core" }
tsan-tsduck-sys = { path = "../tsan-tsduck-sys", optional = true }
